// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Calidad.Data;

#nullable disable

namespace Proyecto_Calidad.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250915202752_Migracion1")]
    partial class Migracion1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Calidad.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dni");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Calificacion", b =>
                {
                    b.Property<int>("IdCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalificacion"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCalificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.Property<int>("estudiante_CursoId")
                        .HasColumnType("int");

                    b.Property<int>("promedioAcumulado")
                        .HasColumnType("int");

                    b.HasKey("IdCalificacion");

                    b.HasIndex("estudiante_CursoId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Comportamiento", b =>
                {
                    b.Property<int>("IdComportamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComportamiento"));

                    b.Property<string>("Calificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("estudiante_CursoId")
                        .HasColumnType("int");

                    b.HasKey("IdComportamiento");

                    b.HasIndex("estudiante_CursoId");

                    b.ToTable("Comportamientos");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HorarioFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCurso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdDocente");

                    b.HasIndex("CursoId");

                    b.HasIndex("UserId");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorIdTutor")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("TutorIdTutor");

                    b.HasIndex("UserId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Estudiante_Curso", b =>
                {
                    b.Property<int>("IdEstudianteCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudianteCurso"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEstudianteCurso");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Estudiantes_Cursos");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("TutorId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Tutor", b =>
                {
                    b.Property<int>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTutor"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTutor");

                    b.HasIndex("UserId");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Calificacion", b =>
                {
                    b.HasOne("Proyecto_Calidad.Models.Estudiante_Curso", "Estudiante_Curso")
                        .WithMany("Calificaciones")
                        .HasForeignKey("estudiante_CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante_Curso");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Comportamiento", b =>
                {
                    b.HasOne("Proyecto_Calidad.Models.Estudiante_Curso", "Estudiante_Curso")
                        .WithMany()
                        .HasForeignKey("estudiante_CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante_Curso");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Docente", b =>
                {
                    b.HasOne("Proyecto_Calidad.Models.Curso", "Curso")
                        .WithMany("Docentes")
                        .HasForeignKey("CursoId");

                    b.HasOne("Proyecto_Calidad.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Estudiante", b =>
                {
                    b.HasOne("Proyecto_Calidad.Models.Tutor", null)
                        .WithMany("Estudiantes")
                        .HasForeignKey("TutorIdTutor");

                    b.HasOne("Proyecto_Calidad.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Estudiante_Curso", b =>
                {
                    b.HasOne("Proyecto_Calidad.Models.Curso", "Curso")
                        .WithMany("estudiante_Curso")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Calidad.Models.Estudiante", "Estudiante")
                        .WithMany("Estudiante_Cursos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Notificacion", b =>
                {
                    b.HasOne("Proyecto_Calidad.Models.Tutor", "Tutor")
                        .WithMany("Notificaciones")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Tutor", b =>
                {
                    b.HasOne("Proyecto_Calidad.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Curso", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("estudiante_Curso");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Estudiante", b =>
                {
                    b.Navigation("Estudiante_Cursos");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Estudiante_Curso", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("Proyecto_Calidad.Models.Tutor", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
